deployment:
  image:
    artifact: ghcr.io/cnie-es/contract-billing-contract
    tag: 2.9.0
    pullPolicy: Always
  replicas: 1
  mode: PROVIDER
  db:
    url: jdbc:postgresql://postgresql.be-common.svc.cluster.local/simpl_contract
    user: postgres
  kafka:
    bootstrapServer: kafka.be-common.svc.cluster.local:9092
    clientUser: user1
    securityProtocol: SASL_PLAINTEXT
    sasl:
      mechanism: PLAIN
    topics:
      signContractRequest: sign-contract-req
      signContractRequestDLT: sign-contract-req-dlt
      signContractResponse: sign-contract-resp
      signContractResponseDLT: sign-contract-resp-dlt
      statusUpdate: status-update
      statusUpdateDLT: status-update-dlt
      searchContractRequest: search-contract-req
      searchContractRequestDLT: search-contract-req-dlt
      searchContractResponse: search-contract-resp
      searchContractResponseDLT: search-contract-resp-dlt
      createContractRequest: create-contract-req
      createContractRequestDLT: create-contract-req-dlt
      createContractResponse: create-contract-resp
      createContractResponseDLT: create-contract-resp-dlt
  urls:
    stubs: 'http://simpl-stubs:8080'
    edc: 'http://simpl-stubs:8080'
    catalogSearch: ''
    catalogGet: ''
  vault:
    hashicorp:
      role: ""
      service: "https://vault.tools.simpl-europe.eu/"
      secretEngine: kv
      secretConfigPath: "{{ .Values.deployment.vault.hashicorp.secretEngine }}/contract"
  otel:
    endpoint: "http://collector.common01.dev.simpl-europe.eu/"
  paymentApproval:
    enabled: true
    expirationDays: 7
    checkIntervalMs: 60000

environment: default
resources:
  requests:
    memory: "300Mi"
    cpu: "150m"
  limits:
    memory: "700Mi"
    cpu: "300m"

probe:
  endpoint: "/contract/v1/health"
  scheme: HTTP
  port: 8080

ingress:
   enabled: false
   annotations:
     kubernetes.io/ingress.class: apisix
   hosts: []
   tls: []

imagePullSecrets:
  - name: github-registry-secret
