cliEnabled: true
gitopsWorkflowImage: ghcr.io/cnie-es/infrastructure-infrastructure-crossplane-gitops:2.1.2
observerImage: ghcr.io/cnie-es/infrastructure-infrastructure-crossplane-observer:2.1.2

kafkaAuthEnable: true
kafkaAuthMechanism: PLAIN
kafkaProvisioningRequestsTopicName: to-provision
kafkaProvisioningResponsesTopicName: provisioned
kafkaDecommissioningRequestsTopicName: to-decommission
kafkaDecommissioningResponsesTopicName: decommissioned

configuration:
  packages:
    - ghcr.io/cnie-es/infrastructure-infrastructure-crossplane-configuration:2.1.2
imagePullSecrets:
  - name: github-registry-secret
