apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart-version: {{ .Chart.Version }}
  name: {{ .Chart.Name }}-configmap
data:
  APP_NAME: "{{ .Chart.Name }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.environment }}"
  PAYMENT_APPROVAL_ENABLED: "{{ .Values.deployment.paymentApproval.enabled }}"
  PAYMENT_APPROVAL_EXPIRATION_DAYS: "{{ .Values.deployment.paymentApproval.expirationDays }}"
  PAYMENT_APPROVAL_CHECK_INTERVAL_MS: "{{ .Values.deployment.paymentApproval.checkIntervalMs }}"
