{{- if .Values.embeddedCommon.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: openbao-sa-token
  namespace: {{ .Values.cluster.namespace }}
  annotations:
    kubernetes.io/service-account.name: openbao-sa
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/service-account-token
{{- end }}
