apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if and .Values.ingress.clusterIssuer (not (.Values.ingress.tls | default dict).secretName) }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    acme.cert-manager.io/http01-edit-in-place: "true"
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "nginx-chart.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ (.Values.ingress.tls | default dict).secretName | default .Values.ingress.secretName }}
